
package climateControl.customGenLayer;

import climateControl.api.Climate;
import climateControl.api.ClimateControlSettings;
import climateControl.api.IslandClimateMaker;
import climateControl.genLayerPack.GenLayerPack;
import com.Zeno410Utils.IntRandomizer;
import git.jbredwards.subaquatic.mod.common.init.SubaquaticBiomes;
import net.minecraft.init.Biomes;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.gen.layer.GenLayer;
import net.minecraft.world.gen.layer.IntCache;

/**
 *
 * @author Zeno410
 */
public class GenLayerBandedClimate extends GenLayerPack implements IslandClimateMaker {

    private final int bandWidth;
    private final int [] bandClimate = new int[6];
    private final int offset;
    private final boolean frozenIcecaps;
    private final boolean separateLandmasses;

    public GenLayerBandedClimate(long par1, GenLayer par3GenLayer,ClimateControlSettings settings, int multiplier)
    {
        super(par1);
        this.parent = par3GenLayer;
        this.offset = settings.bandedClimateOffset.value()*multiplier -multiplier/2;
        this.bandWidth = settings.bandedClimateWidth.value()*multiplier;
        bandClimate[0] = 2;// warm
        bandClimate[1] = 1;// hot
        bandClimate[2] = 2;// warm
        bandClimate[3] = 3;// cool
        bandClimate[4] = 4;// snowy
        bandClimate[5] = 3;// cool
        this.frozenIcecaps = settings.frozenIcecaps.value();
        this.separateLandmasses = settings.separateLandmasses.value();
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int areaX, int areaY, int areaWidth, int areaHeight){
        int[] biomeIds = this.parent.getInts(areaX, areaY, areaWidth, areaHeight);
        int[] Out = new int[areaWidth * areaHeight];

        for (int z = 0; z < areaHeight; ++z)
        {
            for (int x = 0; x < areaWidth; ++x)
            {
                int latitude = areaY+z+offset;
                int band = 0;
                if (latitude >=0) {
                    // positive
                    band = latitude/bandWidth;
                    band = band%6;
                } else {
                    //negative; have to adjust for rounding towards zero
                    band = (latitude-bandWidth+1)/bandWidth;
                    band = band%6;
                    if (band <-5) {
                        throw new RuntimeException(""+latitude + " " + band);
                    }
                    // adjust the lower cool to be band 0
                    if (band <0) band +=6;
                }
                if (biomeIds[x + z * areaWidth] == Biome.getIdForBiome(Biomes.OCEAN)) {
                    if (this.frozenIcecaps&&bandClimate[band]==4) {
                        Out[x + z *areaWidth] = Biome.getIdForBiome(Biomes.FROZEN_OCEAN);
                    }
                    else {
                        Out[x + z *areaWidth] = 0;
                    }
                }
                else {
                    Out[x + z *areaWidth] = bandClimate[band];
                    if (separateLandmasses) {
                        Out[x + z *areaWidth] += biomeIds[x + z * areaWidth]*4;
                    }
                }

            }
        }

        return Out;
    }

    public int climate(int x, int latitude, IntRandomizer randomizer) {
            int band = 0;
            latitude += offset;
            if (latitude >=0) {
                // positive
                band = (latitude)/bandWidth;
                band = band%6;
            } else {
                //negative; have to adjust for rounding towards zero
                band = (latitude-bandWidth+1)/bandWidth;
                band = band%6;
                if (band <-5) {
                    throw new RuntimeException(""+latitude + " " + band);
                }
                // adjust the negatives
                if (band <0) band +=6;
            }
            return bandClimate[band];
    }
}